package io.github.hiskrtapps.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="awscodestar-claranet-snsk_Message")
public class Message {

    private String id;

    private Long recentness;

    private String userId;

    private String createdAt;

    private String message;

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName="id")
    public String getId() { return id; }
    public void setId(String id) {this.id = id; }

    @DynamoDBRangeKey(attributeName="recentness")
    public Long getRecentness() {return recentness; }
    public void setRecentness(Long recentness) { this.recentness = recentness; }

    @DynamoDBAttribute(attributeName="userId")
    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }

    @DynamoDBAttribute(attributeName="createdAt")
    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }

    @DynamoDBAttribute
    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }
}